/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jivesoftware_spark_plugin_flashing_FlashWindow */

#ifndef _Included_org_jivesoftware_spark_plugin_flashing_FlashWindow
#define _Included_org_jivesoftware_spark_plugin_flashing_FlashWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jivesoftware_spark_plugin_flashing_FlashWindow
 * Method:    flash
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_org_jivesoftware_spark_plugin_flashing_FlashWindow_flash
  (JNIEnv *, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
