/**
 * Copyright (C) 2004-2010 Jive Software. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.jivesoftware.spark.plugin.galene;

import javax.swing.ImageIcon;

import org.jivesoftware.spark.component.RolloverButton;
import org.jivesoftware.spark.ui.ChatRoom;
import org.jivesoftware.spark.util.*;
import org.jivesoftware.spark.util.log.*;
import org.jivesoftware.smack.packet.*;

import javax.xml.bind.DatatypeConverter;
import org.jivesoftware.resource.SparkRes;

public class ChatRoomDecorator
{
    public RolloverButton galeneButton;
    public final ChatRoom room;
	public static String ICON_STRING = "R0lGODlhEAAQAPcAAABvrgB0rwB9AACBTQCDAACHRACMjACZnwCggACqdQdspRKidB2neiG0hi9BnjI+njVUrDZJqTdiqDlypToUmEB+q0FFoUGhm0R3p1Y+nVmlR1yqjV2qF19HmmBYpWO5nXaqsHvLAH8Qk39ii4B0mYG3VYLGAIMznYUFlIe0NojIFIvMRozHr4zKPo/JsJHKOpHNN5LKRJLMSphgqppdpprKOprRVJvPYZ++RZ/ROKOIu6V2taaXiKlFj6yUiK2PxLGlxrMtf7OaxrOlyrSSxry5X73ZML3gpb7aL7/c0L/eo8HfqcKqzsbh1cvc0cyJAMzay87fAM/lvNDlvdDoNNGRQNLiKtLjJdPE3tW4LNXlMdigZdjkItqCcdrc59viL9vsz93r5t9/LuB4OuDSAOEAP+Hv1+IAAOZEM+ZIEuff7OgAA+ljMelwKumzR+nh7upLAOpbAOpuHupxP+qhJureAOteLuuBL+u5AOvz7OyDA+zkH+zor+2AWe3U2u3s8+346+9mPu/Cs+/s7vCLJ/D37PGzOvHIL/HxwvLv9fO7U/O8IPWsAPW0APXAHPXv4PX68/bR0PfPlff5+fjWqvjbAPjiS/ji3vnIi/nVpvneHfnfSvriG/vut/zmEPz39f323/369f6+AP7+/v/65gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAAKUAIf/8SUNDUkdCRzEwMTIAABfYYXBwbAIQAABtbnRyUkdCIFhZWiAH2gADAB0ADwAcACVhY3NwQVBQTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9tYAAQAAAADTLWFwcGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFkZXNjAAABUAAAAGJkc2NtAAABtAAAADBjcHJ0AAAB5AAAANB3dHB0AAACtAAAABRyWFlaAAACyAAAABRnWFlaAAAC3AAAABRiWFlaAAAC8AAAABRyVFJDAAADBAAACAxhYXJnAAALEAAAACB2/2NndAAACzAAAAYSbmRpbgAAEUQAAAY+Y2hhZAAAF4QAAAAsbW1vZAAAF7AAAAAoYlRSQwAAAwQAAAgMZ1RSQwAAAwQAAAgMYWFiZwAACxAAAAAgYWFnZwAACxAAAAAgZGVzYwAAAAAAAAAIRGlzcGxheQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG1sdWMAAAAAAAAAAgAAAAxlblVTAAAACAAAAChwdEJSAAAACAAAACgAaQBNAGEAY3RleHQAAAAAQ29wef9yaWdodCBBcHBsZSwgSW5jLiwgMjAxMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWFlaIAAAAAAAAPNSAAEAAAABFs9YWVogAAAAAAAAelIAAD9fAAABcVhZWiAAAAAAAABZpQAArX8AABn/EFhZWiAAAAAAAAAi3wAAEyIAALisY3VydgAAAAAAAAQAAAAABQAKAA8AFAAZAB4AIwAoAC0AMgA2ADsAQABFAEoATwBUAFkAXgBjAGgAbQByAHcAfACBAIYAiwCQAJUAmgCfAKMAqACtALIAtwC8AMEAxgDLANAA1QDbAOAA5QDrAPAA9gD7AQEBBwENARMBGQEfASUBKwEyATgBPgFFAUwBUgFZAWABZwFuAXUBfAGDAYsBkgGaAaEBqQGxAbkBwQHJAdEB2QHhAekB8gH6AgMCDAIUAh0CJgIvAjgCQQJLAlQCXQJnAnECegKEAo4CmAKiAqwCtgLBAssC1QLg/wLrAvUDAAMLAxYDIQMtAzgDQwNPA1oDZgNyA34DigOWA6IDrgO6A8cD0wPgA+wD+QQGBBMEIAQtBDsESARVBGMEcQR+BIwEmgSoBLYExATTBOEE8AT+BQ0FHAUrBToFSQVYBWcFdwWGBZYFpgW1BcUF1QXlBfYGBgYWBicGNwZIBlkGagZ7BowGnQavBsAG0QbjBvUHBwcZBysHPQdPB2EHdAeGB5kHrAe/B9IH5Qf4CAsIHwgyCEYIWghuCIIIlgiqCL4I0gjnCPsJEAklCToJTwlkCXkJjwmkCboJzwnlCfsKEQonCj0KVApqCoEKmAquCsUK3ArzCwsLIgs5C/9RC2kLgAuYC7ALyAvhC/kMEgwqDEMMXAx1DI4MpwzADNkM8w0NDSYNQA1aDXQNjg2pDcMN3g34DhMOLg5JDmQOfw6bDrYO0g7uDwkPJQ9BD14Peg+WD7MPzw/sEAkQJhBDEGEQfhCbELkQ1xD1ERMRMRFPEW0RjBGqEckR6BIHEiYSRRJkEoQSoxLDEuMTAxMjE0MTYxODE6QTxRPlFAYUJxRJFGoUixStFM4U8BUSFTQVVhV4FZsVvRXgFgMWJhZJFmwWjxayFtYW+hcdF0EXZReJF64X0hf3GBsYQBhlGIoYrxjVGPoZIBlFGWsZkRm3Gd0aBBoqGlEadxqeGsX/GuwbFBs7G2MbihuyG9ocAhwqHFIcexyjHMwc9R0eHUcdcB2ZHcMd7B4WHkAeah6UHr4e6R8THz4faR+UH78f6iAVIEEgbCCYIMQg8CEcIUghdSGhIc4h+yInIlUigiKvIt0jCiM4I2YjlCPCI/AkHyRNJHwkqyTaJQklOCVoJZclxyX3JicmVyaHJrcm6CcYJ0kneierJ9woDSg/KHEooijUKQYpOClrKZ0p0CoCKjUqaCqbKs8rAis2K2krnSvRLAUsOSxuLKIs1y0MLUEtdi2rLeEuFi5MLoIuty7uLyQvWi+RL8cv/jA1MGwwpDDbMRIxSjGCMbox8jIqMmMy/5sy1DMNM0YzfzO4M/E0KzRlNJ402DUTNU01hzXCNf02NzZyNq426TckN2A3nDfXOBQ4UDiMOMg5BTlCOX85vDn5OjY6dDqyOu87LTtrO6o76DwnPGU8pDzjPSI9YT2hPeA+ID5gPqA+4D8hP2E/oj/iQCNAZECmQOdBKUFqQaxB7kIwQnJCtUL3QzpDfUPARANER0SKRM5FEkVVRZpF3kYiRmdGq0bwRzVHe0fASAVIS0iRSNdJHUljSalJ8Eo3Sn1KxEsMS1NLmkviTCpMcky6TQJNSk2TTdxOJU5uTrdPAE9JT5NP3VAnUHFQu1EGUVBRm1HmUjFSfFLHUxNTX/9TqlP2VEJUj1TbVShVdVXCVg9WXFapVvdXRFeSV+BYL1h9WMtZGllpWbhaB1pWWqZa9VtFW5Vb5Vw1XIZc1l0nXXhdyV4aXmxevV8PX2Ffs2AFYFdgqmD8YU9homH1YklinGLwY0Njl2PrZEBklGTpZT1lkmXnZj1mkmboZz1nk2fpaD9olmjsaUNpmmnxakhqn2r3a09rp2v/bFdsr20IbWBtuW4SbmtuxG8eb3hv0XArcIZw4HE6cZVx8HJLcqZzAXNdc7h0FHRwdMx1KHWFdeF2Pnabdvh3VnezeBF4bnjMeSp5iXnnekZ6pXsEe2N7wnwhfIF84X1BfaF+AX7/Yn7CfyN/hH/lgEeAqIEKgWuBzYIwgpKC9INXg7qEHYSAhOOFR4Wrhg6GcobXhzuHn4gEiGmIzokziZmJ/opkisqLMIuWi/yMY4zKjTGNmI3/jmaOzo82j56QBpBukNaRP5GokhGSepLjk02TtpQglIqU9JVflcmWNJaflwqXdZfgmEyYuJkkmZCZ/JpomtWbQpuvnByciZz3nWSd0p5Anq6fHZ+Ln/qgaaDYoUehtqImopajBqN2o+akVqTHpTilqaYapoum/adup+CoUqjEqTepqaocqo+rAqt1q+msXKzQrUStuK4trqGvFq+LsACwdbDqsWCx1rJLssKzOLOu/7QltJy1E7WKtgG2ebbwt2i34LhZuNG5SrnCuju6tbsuu6e8IbybvRW9j74KvoS+/796v/XAcMDswWfB48JfwtvDWMPUxFHEzsVLxcjGRsbDx0HHv8g9yLzJOsm5yjjKt8s2y7bMNcy1zTXNtc42zrbPN8+40DnQutE80b7SP9LB00TTxtRJ1MvVTtXR1lXW2Ndc1+DYZNjo2WzZ8dp22vvbgNwF3IrdEN2W3hzeot8p36/gNuC94UThzOJT4tvjY+Pr5HPk/OWE5g3mlucf56noMui86Ubp0Opb6uXrcOv77IbtEe2c7ijutO9A78zwWPDl8XLx//KM8xnzp/Q09P/C9VD13vZt9vv3ivgZ+Kj5OPnH+lf65/t3/Af8mP0p/br+S/7c/23//3BhcmEAAAAAAAMAAAACZmYAAPKnAAANWQAAE9AAAArAdmNndAAAAAAAAAAAAAMBAAACAAAAAgAIABQAJQA8AFoAfgCpANsBHgF+AekCbwMIA7wEggVoBmwHgQi3CgcLawziDmIP7RGHEx0UshZNF9oZahr7HIkeGx+yIU4i7SSWJkMn7CmSK0Is7y6fMEYx7DORNTM2yjhfOeQ7bTzpPl4/z0FBQp1D8UUmRldHiEi1SeRLEEw4TWNOhk+pUM1R7lMNVCtVRVZfV3tYl1mxWsxb5V0CXhz/Xz1gYGGCYp9jvmTaZfFnCGgcaS5qPmtNbFltZm50b35wjHGccqpzuXTMddp23XfbeNl52HrYe9p8233dfuJ/6YDygfyDCYQahS2GQoddiHqJmYq3i9iM/o4ij0iQbpGaksOT7pUalkWXbpiVmbaa2pv8nRieNJ9LoGChcqKAo5qkrKXDptWn6Kj2qgKrDKwTrRiuG68csBqxFbIQswq0AbT5tfS29bf/uQi6ELsWvBq9HL4bvxrAGMEVwhHDDcQKxQfGBccDyATJAMnqysDLlMxozT7OFc7sz8bQpNGC0mPTR9Qt1RTV/9bp19fYydms2nXbNtv43MDdid5W3yXf//XgyOGc4nDjQ+QV5Ojlt+aE50/oDuiu6Ubp2epu6wTrm+w17NHtb+4O7q/vUu/28JzxQvHp8pDzO/Pp9Jn1SfX59qr3W/gM+MD5dfos+uX7o/xj/Sb97/63/2P//wAAAAIABwASACIAOABTAHUAnQDLAQABVQG0AiECogM1A+MEsQWdBqEHvQj6CloLwA06Dr8QSxHTE2IU7BZoF+IZWxrOHE4dyB9KINEiXSPuJXsnCiifKjIrxy1YLuMwbDHzM3E06jZZN8Y5LzqKO+Q9PT6BP71A4kIAQxxENkVRRmpHfUiQSaFKsEu+TMlN0k7aT99Q41HoUuxT71TzVfRW+P9X/VkOWiVbOFxKXV5ecF99YIlhlmKeY6ZkrGWyZrdnvmjCaclq0WvZbOJt7W7xb+hw2nHKcrpzrHSgdZR2iHd+eHd5cXpre2h8aX1rfm9/eICDgY+CmoOlhLCFuYbEh9KI5Yn5iw6MJ41BjlyPdJCMkaWSv5PSlOiV+pcKmBiZJZo3m0icW51tnn2fiqCXoaGiqaOvpLSluKa3p7Wos6mxqqirpKyeraaus6/CsNCx3LLns++09rX9twO4CbkOuhG7FrwavR++Jb8swC/BKsIbwwnD+cTlxdTGwcevyJ/Jj8qAy3LMZM1Yzk3PQ9A70TXSKtMX1ADU6dXZ1sbXtdj/o9mT2oLbb9xb3UTeKt8P3/Hg0eGs4objX+Q35RDl4+a354foVeki6e3qtOt47Dzs/u3A7oDvQfAC8MzxsvKi84/0e/Vm9k33MPgR+O/5x/qe+3P8Rf0V/ef+tf9j//8AAAABAAcAEAAfADIASwBpAI0AtgDmASYBegHXAkYCyANbBAAEwgWSBncHcwh+CZcKugvnDRoOTQ+EELcR6RMWFD0VbhadF8wZAho7G3scvh4AH0AggiHHIwskTyWOJssoBik8Km0rliy+LeAu+jASMSsyNDM2NCM1DjX2Nt03xDiqOY06bjtMPCw9CT3lPr8/mEBwQUZCHELzQ8lEnkVz/0ZLRyBIBkjwSdhKwUuqTJNNek5gT0ZQK1ERUfdS3FPCVKtVk1Z8V2lYVVlCWjJbGFvvXMBdkF5fXzBgAWDTYaVieGNNZCJk92XPZqhng2hfaT9qIGsAa+Bsum2Obl1vL3ACcNhxsXKKc2V0QXUddfV2zHejeHl5SnoZeuR7rXxzfUV+On83gDWBMYIqgyCEFYUGhfWG4ofOiLqJooqKi3OMW41CjiyPGJAPkRCSEZMRlBCVDpYKlwWYAJj9mfua+pv6nP2eAZ8JoBOhIKIqoySkD6T4peSmz6e+qK6po6qcq5isma2erqavsLDBsdGy5rP+tQy2CLb9t/W49bn3uv/9vAe9Fb4lvzjASsFcwm3DfcSLxZfGn8elyMHJ38sDzCLNRs5mz4fQqdHL0uzUDNUs1kzXbdiO2azaztv13U/etOAc4Y3jDeSd5kLoBenl6+3uGfBw8uf1iPhP+zD+Iv//AABuZGluAAAAAAAABjYAAKXwAABXAwAASikAAJpRAAAkgQAAEjMAAFANAABUOQAC1HoAAn1wAAGrhQADAQAAAgAAADEAUgBuAIgAoQC3AM4A5AD5AQ4BIwE4AU0BYwF4AY8BpQG8AdQB7AIGAh8COgJWAnICkAKtAswC6wMLAysDTANtA48DsQPTA/YEGQQ9BGIEiASuBNQE+wUjBUv/BXQFnwXKBfYGIwZQBn8GrwbhBxMHSAd+B7QH7AgnCGMIoAjfCR4JYgmoCfEKRAqXCusLQwuaC/QMUAyvDQ4NcQ3WDjwOpA8PD3wP6xBdENERRhG8EjUSrxMsE6oUKBSrFSoVqxYuFrUXPRfHGFUY5xl6GhEaqxtIG+ccih0uHdQefh8oH9IgfyEvId0ijiNJJAwk0SWZJmInKyf3KMUplCpiKzIsAizULaQucy9FMBUw5DGzMoMzVjQpNPk1zDaiN3c4TzkjOfw61TuwPIs9aj5MPzFAHEEHQfJC6UPeRNlF2kbdR+ZI9Un5SwhME00lTjhPUlByUZJSvFPoVRtW/1BXi1jPWhVbXFyuXgFfU2ChYeNjKmRxZb9nEGhoacVrJ2yLbfRvX3DQckBztXUpdqB4FXmOeyZ88H7BgJaCZ4Q9hhCH3omui3iNQY8MkM+SmZRclhyX/ZoynHKenqDLovClE6czqVSreq2or9iyFrRctra5q7ztwCnDYcaHyanMxM/a0unV/tkT3A/fCOIM5Q3oFesW7hLxB/Pr9sn5k/xe//8AAAA1AFoAewCYALIAygDiAPkBDwEkAToBUAFmAXwBkwGqAcIB2wH0Ag4CKQJGAmMCggKhAsIC4wMEAyYDSgNtA5EDtQPaA/8EJQRMBHQEnATEBO4FGAVDBW4Fm/8FyQX4BigGWQaLBr8G9AcrB2QHngfZCBYIVgiYCNoJHglnCbIKAgpbCrMLDwttC8wMLQySDPkNYg3ODjwOrQ8hD5cQEBCNEQsRixIOEpMTGhOlFC4UuxVAFccWUhbfF20X/hiTGSsZxBpiGwIbphxLHPUdnR5LHvkfqCBZIQwhwCJ1IzYkAyTTJacmfCdRKCkpAyneKrkrlSxzLVEuLi8ML+swyDGlMoQzZjRJNS82GTcDN+441zm/Oqo7lDx+PWk+Vj9HQDtBL0IjQyFEHUUeRiVHLkg9SUxKVktoTHdNjE6jT8BQ4FIEUy1UW1WMVr9X/Fk9WoBbxl0XXmVft2D/+WI4Y3hkuWYBZ0pommnua0Vsn238b1twwXImc5B0+XZmd9F5QXq7fEx97H+HgS2C0oR9hieH0omBiy+M346QkEKR9JOolVaXCpjVmqycip5boDOiC6PqpcSnp6mOq4Cte698sYqznrXEt++6I7xWvp3A5sNCxaXIF8qXzSbPwNJf1QfXttpH3HzequDn4yblb+fJ6i7soO8l8bX0Ufb7+ab8YP//AAAAOwBlAIkAqgDIAOYBAgEeAToBVgFzAZABrgHNAe0CDgIxAlUCewKjAssC9AMfA0sDdwOkA9EEAAQuBF8EkQTEBPcFLAViBZkF0gYNBkkGhwbHBwkHTgeW/wfeCCsIewjNCSAJegnYCkEKrQsdC5AMBQx/DPwNfg4CDooPFg+mEDoQ0hFtEgsSrBNSE/gUoxVCFeMWiBcvF9gYhhk3GesaohtbHBcc1x2WHlkfHR/hIKghcSI5Iw8j+yTsJeIm2SfSKM8pzirOK9Es1i3aLuAv6DDtMfQy/zQQNTA2XDeHOLI52zsGPDI9Xz6RP8xBCkJOQ51E80ZWR8JJHko7S2JMiE21TuhQIlFfUqZT8FVBVpRX71lPWq9cFF1+XuVgS2GXYudkOWWPZupoSGmsaxNsem3jb0twtnIfc4l08HZYd7x5IXqUfCp91X93gSCCxYRqhgqHpIk9iv3QjGCN7Y97kP+SipQPlY+XGJjCmoOcR537n66hXqMJpLGmVqf7qaCrSKz1rqSwV7IQs8+1mLdkuQy6uLxZvgm/sMFewxDEw8Z0yCrJ48ugzV3PHdDh0qLUaNY01/zZw9tJ3MPeOd+w4SPijePv5Unmmufh6R/qTOtw7I7tne6n76rwofGU8nvzYfRB9R/19fbJ95X4X/kn+ez6sPtx/DP87/2p/pL//wAAc2YzMgAAAAAAAQxCAAAF3v//8yYAAAeSAAD9kf//+6L///2jAAAD3AAAwGxtbW9kAAAAAAAABhAAAJxrAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAAEAAQAAAI7wBHCRz4x0+kS58GKhSoRkiPM2fS9BEEaeEoLDtOBFlTBo0cOFsAKcRChAaKGV303GEzJ06RiqPe/NAhgskjS5w0LWoT6MkRgUMyUAAyilSlo54c2RETo1AiDxY6DBIIqtOmOnsIjTEBxosDCCMyKUQUhQqdKiGmeHkQgUQjSqEE8omiJQuOEFLyTJCAwU0jRZIwkblyJccKrqNAKAjAQ1QjRniscEHS4kXTUU0MVADgw9ChL1eMvJBhQslAFwguHNhQIkWNFjJU3IA5ahKLBA0YFBigAYaJG3ksJvmwgIAADjaW0F44KYwTKGaWjwoIADs=";

    public ChatRoomDecorator(final ChatRoom room, final SparkGalenePlugin plugin)
    {
        this.room = room;

        try {
            byte[] imageByte = DatatypeConverter.parseBase64Binary(ICON_STRING);
            ImageIcon galeneIcon = new ImageIcon(imageByte);
            galeneButton = new RolloverButton(galeneIcon);
            galeneButton.setToolTipText(GraphicUtils.createToolTip(SparkGaleneResource.getString("name")));
            final String roomId = getNode(room.getBareJid().toString());
            final String sessionID = roomId + "/" + System.currentTimeMillis();

            galeneButton.addActionListener(event -> {
                String newUrl, newRoomId;

                if ("groupchat".equals(room.getChatType().toString())) {
                    newRoomId = sessionID;
                    newUrl = plugin.url + "?room=" + newRoomId;
                    plugin.handleClick(newUrl, room, newUrl, Message.Type.groupchat);

                } else {
                    newRoomId = sessionID;
                    newUrl = plugin.url + "?room=" + newRoomId;
                    plugin.handleClick(newUrl, room, newUrl, Message.Type.chat);
                }
            });
            room.getEditorBar().add(galeneButton);

        } catch (Exception e) {
            Log.error("cannot create galene webinar icon", e);
        }

    }

    public void finished()
    {
        Log.warning("ChatRoomDecorator: finished " + room.getBareJid());
    }

    private String getNode(String jid)
    {
        String node = jid;
        int pos = node.indexOf("@");

        if (pos > -1)
            node = jid.substring(0, pos);

        return node;
    }
}
